# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none

jobs: 
  - job: macOS10_14Build
    pool:
      vmImage: 'macOS-10.14'
    strategy:
      matrix:
        Python38_macOS1014:
          python.version: '3.8'
        Python39_macOS1014:
          python.version: '3.9'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install numpy
      displayName: 'Install dependencies'
    - script: |
        pip install wheel twine
      displayName: 'Install build tools'
    - script: |
        python setup.py sdist bdist_wheel
        twine upload -r pypi -u $(twineUsername) -p $(twinePassword) --skip-existing --disable-progress-bar dist/*
      displayName: 'Publish wheel to PyPi'
  
  - job: Aarch64_Manylinux2014Build
    pool:
      vmImage: 'ubuntu-18.04'
    strategy:
      matrix:
        Py35 Arm64:
          python.code: 'cp35-cp35m'
          manylinux: 'manylinux_aarch64'
        Py36 Arm64:
          python.code: 'cp36-cp36m'
          manylinux: 'manylinux_aarch64'
        Py37 Arm64:
          python.code: 'cp37-cp37m'
          manylinux: 'manylinux_aarch64'
        Py38 Arm64:
          python.code: 'cp38-cp38'
          manylinux: 'manylinux_aarch64'
        Py39 Arm64:
          python.code: 'cp39-cp39'
          manylinux: 'manylinux_aarch64'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
        ${{ if ne(parameters.architecture, '') }}:
          architecture: ${{ parameters.architecture }}
    - script: docker run --rm --privileged hypriot/qemu-register
      displayName: 'Registering qemu'
    - script: |
        set -xeo pipefail
        docker run -v $(pwd):"${DOCKER_ROOT_DIRECTORY}":rw,z \
                   -e HOST_USER_ID \
                    "arm64v8/ubuntu:bionic" \
                    bash -c "cd $DOCKER_ROOT_DIRECTORY;
                    apt-get update -qq && apt-get install -qq make $PYTHON python3-pip lib$PYTHON-dev git && \
                    $PYTHON -m pip install --upgrade pip setuptools wheel pytest-azurepipelines twine && \
                    $PYTHON -m pip wheel . -w wheelhouse/"
      displayName: 'Running AArch64 build'
      env:
        DOCKER_ROOT_DIRECTORY: "/home/source_root"
        HOST_USER_ID: $(id -u)
        PYTHON: "python$(python.version)"
      
  - job: Manylinux2010Build
    pool:
      vmImage: 'ubuntu-16.04'
    container: quay.io/pypa/manylinux2010_x86_64:latest
    variables:
      python: /opt/python/cp37-cp37m/bin/python
    steps:
    - script: |
        for PYBIN in /opt/python/*/bin; do
          "${PYBIN}/pip" install --user numpy twine
        done
      displayName: 'Install dependencies and build tools'
    - script: |
        for PYBIN in /opt/python/*/bin; do
          "${PYBIN}/pip" wheel . -w wheelhouse/
        done
      displayName: 'Build wheels'
    - script: |
        for whl in wheelhouse/deap*.whl; do
          auditwheel repair "$whl" --plat manylinux2010_x86_64 -w wheelhouse-manylinux/
        done
      displayName: 'Audit wheels'
    - script: |
        $(python) -m twine upload -r pypi -u $(twineUsername) -p $(twinePassword) --skip-existing --disable-progress-bar wheelhouse-manylinux/*
      displayName: 'Publish wheel to PyPi'
